# Copyright (c) 2024 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
{{- $releaseName := .Release.Name -}}
{{- $name := include "ditto.name" . -}}
{{- $labels := include "ditto.labels" . -}}
{{ $root := . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-service-config-connectivity-extension-conf
  namespace: {{ $root.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}-service-config-connectivity-extension-conf
{{ $labels | indent 4 }}
data:
  connectivity-extension.conf: |-
{{ tpl ($root.Files.Get "service-config/connectivity-extension.conf.tpl") $ | indent 4 }}
---