# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
{{- if .Values.global.logging.customConfigFile.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $name := include "ditto.name" . -}}
{{- $labels := include "ditto.labels" . -}}
{{- $logbackFileName := .Values.global.logging.customConfigFile.fileName -}}
{{ $root := . }}
{{ range $path, $bytes := .Files.Glob "logback-config/**" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $path | replace "/" "-" | replace "." "-" }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}-logback-config
{{ $labels | indent 4 }}
data:
  {{ $logbackFileName }}: |-
{{ $root.Files.Get $path | indent 4 }}
---
{{- end -}}
{{- end -}}
